import React, { useState } from "react";
import { api } from "../services/api";
import { useToast } from "../components/Toast";
export default function Profile({ user, onUpdate }) {
  const { push } = useToast(); const [form, setForm] = useState({ name: user.name || "", phone: user.phone || "", address: user.address || "" }); const [password, setPassword] = useState({ currentPassword: "", newPassword: "" }); const [busy, setBusy] = useState(false);
  const saveProfile = async (event) => { event.preventDefault(); try { setBusy(true); const data = await api("/auth/profile", { method: "PATCH", body: JSON.stringify(form) }); onUpdate(data.user); localStorage.setItem("fz_user", JSON.stringify(data.user)); push({ message: "Profile updated", variant: "success" }); } catch (error) { push({ message: error.message, variant: "error" }); } finally { setBusy(false); } };
  const savePassword = async (event) => { event.preventDefault(); try { await api("/auth/password", { method: "PATCH", body: JSON.stringify(password) }); setPassword({ currentPassword: "", newPassword: "" }); push({ message: "Password changed", variant: "success" }); } catch (error) { push({ message: error.message, variant: "error" }); } };
  return <div className="auth-page container"><div className="auth-card"><h2>My profile</h2><p className="muted">{user.email}</p><form className="auth-form" onSubmit={saveProfile}><label>Name<input className="input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Phone<input className="input" inputMode="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Delivery address<textarea className="textarea" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><button className="btn btn-primary" disabled={busy}>{busy ? "Saving…" : "Save profile"}</button></form><hr /><h3>Change password</h3><form className="auth-form" onSubmit={savePassword}><input className="input" required type="password" placeholder="Current password" value={password.currentPassword} onChange={(e) => setPassword({ ...password, currentPassword: e.target.value })} /><input className="input" required minLength="8" type="password" placeholder="New password (8+ characters)" value={password.newPassword} onChange={(e) => setPassword({ ...password, newPassword: e.target.value })} /><button className="btn btn-ghost">Update password</button></form></div></div>;
}
