import React, { useEffect, useMemo, useState } from "react";
import { BrowserRouter as Router, Routes, Route, useLocation, Navigate } from "react-router-dom";
import Navbar from "./components/Navbar"; import Footer from "./components/Footer";
import Home from "./pages/Home"; import Menu from "./pages/Menu"; import Cart from "./pages/Cart"; import Favorites from "./pages/Favorites"; import Orders from "./pages/Orders"; import OrderDetails from "./pages/OrderDetails"; import Login from "./pages/Login"; import Signup from "./pages/Signup"; import Profile from "./pages/Profile"; import Admin from "./pages/Admin"; import ForgotPassword from "./pages/ForgotPassword"; import ResetPassword from "./pages/ResetPassword";
import { ToastProvider, useToast } from "./components/Toast"; import { api } from "./services/api"; import "./App.css";
function RequireAuth({ user, children, adminOnly = false }) { const location = useLocation(); if (!user) return <Navigate to="/login" replace state={{ from: location.pathname }} />; return adminOnly && user.role !== "admin" ? <Navigate to="/" replace /> : children; }
function AppContent() {
  const { push } = useToast(); const [theme, setTheme] = useState(() => localStorage.getItem("fz_theme") || (window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light")); const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem("fz_user")) || null; } catch { return null; } }); const [foods, setFoods] = useState([]); const [cart, setCart] = useState(() => { try { return JSON.parse(localStorage.getItem("fz_cart")) || {}; } catch { return {}; } }); const [favs, setFavs] = useState(() => { try { return JSON.parse(localStorage.getItem("fz_favs")) || {}; } catch { return {}; } });
  useEffect(() => { document.documentElement.classList.toggle("dark", theme === "dark"); localStorage.setItem("fz_theme", theme); }, [theme]); useEffect(() => { localStorage.setItem("fz_cart", JSON.stringify(cart)); }, [cart]); useEffect(() => { localStorage.setItem("fz_favs", JSON.stringify(favs)); }, [favs]); useEffect(() => { api("/foods").then((data) => setFoods(data.foods)).catch(() => {}); }, []);
  const logout = () => { setUser(null); localStorage.removeItem("fz_user"); localStorage.removeItem("fz_token"); }; useEffect(() => { const handler = () => { logout(); push({ message: "Your session has expired. Please sign in again.", variant: "info" }); }; window.addEventListener("swag:unauthorized", handler); return () => window.removeEventListener("swag:unauthorized", handler); }, [push]);
  const login = (nextUser, token) => { setUser(nextUser); localStorage.setItem("fz_user", JSON.stringify(nextUser)); localStorage.setItem("fz_token", token); }; const keyFor = (id, size = "M", addons = []) => `${id}|${size}|${[...addons].sort().join(",")}`; const addConfiguredToCart = (item, config) => { const key = keyFor(item._id, config.size, config.addons); setCart((old) => ({ ...old, [key]: { qty: (old[key]?.qty || 0) + 1, meta: { id: item._id, size: config.size, addons: config.addons } } })); }; const increaseQty = (key) => setCart((old) => ({ ...old, [key]: { ...old[key], qty: Math.min(20, old[key].qty + 1) } })); const decreaseQty = (key) => setCart((old) => { if (old[key].qty > 1) return { ...old, [key]: { ...old[key], qty: old[key].qty - 1 } }; const copy = { ...old }; delete copy[key]; return copy; }); const removeFromCart = (key) => setCart((old) => { const copy = { ...old }; delete copy[key]; return copy; }); const cartCount = useMemo(() => Object.values(cart).reduce((sum, entry) => sum + entry.qty, 0), [cart]); const toggleFav = (id) => setFavs((old) => ({ ...old, [id]: !old[id] }));
  return <><Navbar cartCount={cartCount} theme={theme} setTheme={setTheme} user={user} onLogout={logout} /><Routes><Route path="/" element={<Home />} /><Route path="/menu" element={<Menu cart={cart} getQtyForId={(id) => Object.values(cart).reduce((sum, x) => sum + (String(x.meta.id) === String(id) ? x.qty : 0), 0)} addToCart={(item) => addConfiguredToCart(item, { size: "M", addons: [] })} addConfiguredToCart={addConfiguredToCart} isFav={(id) => !!favs[id]} toggleFav={toggleFav} />} /><Route path="/favorites" element={<RequireAuth user={user}><Favorites favIds={Object.keys(favs).filter((id) => favs[id])} allItems={foods} addToCart={(item) => addConfiguredToCart(item, { size: "M", addons: [] })} addConfiguredToCart={addConfiguredToCart} isFav={(id) => !!favs[id]} toggleFav={toggleFav} /></RequireAuth>} /><Route path="/cart" element={<Cart cart={cart} foodItems={foods} increaseQty={increaseQty} decreaseQty={decreaseQty} removeFromCart={removeFromCart} clearCart={() => setCart({})} user={user} />} /><Route path="/orders" element={<RequireAuth user={user}><Orders /></RequireAuth>} /><Route path="/orders/:id" element={<RequireAuth user={user}><OrderDetails /></RequireAuth>} /><Route path="/profile" element={<RequireAuth user={user}><Profile user={user} onUpdate={setUser} /></RequireAuth>} /><Route path="/admin/*" element={<RequireAuth user={user} adminOnly><Admin /></RequireAuth>} /><Route path="/login" element={<Login onLogin={login} />} /><Route path="/signup" element={<Signup onSignup={login} />} /><Route path="/forgot" element={<ForgotPassword />} /><Route path="/reset" element={<ResetPassword />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes><Footer /></>;
}
export default function App() { return <Router><ToastProvider><AppContent /></ToastProvider></Router>; }
